jobs:
  # Add Chromatic Job
  chromatic-deployment:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
        # Run the Chromatic CLI
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}

workflows:
  # Add Chromatic Workflow
  chromatic-deploy:
    jobs:
      - chromatic-deployment # Runs the Chromatic job implemented above
        filters:
          branches:
            only: main